const lang = {
  en: {
    search: "Search",
    gptSearchPlaceHolder: "What would you like to watch today?",
    gptSearch: "GPT Search",
    welcome: "Welcome",
    signout: "Sign Out",
    signin: "Sign In",
    signup: "Sign Up",
    name: "Name Of User",
    email: "Email",
    password: "Password",
    signinMessage: "New to Netflix? SignUp now",
    signupMessage: "Already registered? SignIn now",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceHolder: "आज आप क्या देखना चाहेंगे?",
    gptSearch: "जीपीटी खोज",
    welcome: "स्वागत",
    signout: "साइन आउट",
    signin: "साइन इन करें",
    signup: "साइन अप करें",
    name: "उपयोगकर्ता का नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    signinMessage: "नेटफ्लिक्स पर नए हैं? अभी साइनअप करें",
    signupMessage: "पहले से ही पंजीकृत? अब साइन इन करो",
  },
  gujarati: {
    search: "શોધો",
    gptSearchPlaceHolder: "તમે આજે શું જોવા માંગો છો?",
    gptSearch: "GPT શોધ",
    welcome: "સ્વાગત છે",
    signout: "સાઇન આઉટ કરો",
    signin: "સાઇન ઇન કરો",
    signup: "સાઇન અપ કરો",
    name: "વપરાશકર્તાનું નામ",
    email: "ઈમેલ",
    password: "પાસવર્ડ",
    signinMessage: "Netflix માટે નવા છો? અત્યારે જોડવ",
    signupMessage: "પહેલેથી નોંધાયેલ છે? હમણાં સાઇન ઇન કરો",
  },
  marathi: {
    search: "शोधा",
    gptSearchPlaceHolder: "तुम्हाला आज काय बघायला आवडेल?",
    gptSearch: "GPT शोध",
    welcome: "स्वागत आहे",
    signout: "साइन आउट करा",
    signin: "साइन इन करा",
    signup: "साइनअप करा",
    name: "वापरकर्त्याचे नाव",
    email: "ईमेल",
    password: "पासवर्ड",
    signinMessage: "Netflix वर नवीन? आत्ताच नोंदणी करा",
    signupMessage: "आधीच नोंदणी झाली आहे? आता साइन इन करा",
  },
  bangla: {
    search: "অনুসন্ধান করুন",
    gptSearchPlaceHolder: "আপনি আজ কি দেখতে চান?",
    gptSearch: "জিপিটি অনুসন্ধান",
    welcome: "স্বাগত",
    signout: "সাইন আউট",
    signin: "সাইন ইন করুন",
    signup: "নিবন্ধন করুন",
    name: "ব্যবহারকারীর নাম",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    signinMessage: "Netflix এ নতুন? এখন সাইন আপ করুন",
    signupMessage: "ইতিমধ্যে নিবন্ধভুক্ত? এখন সাইন ইন করুন",
  },
  punjabi: {
    search: "ਖੋਜ",
    gptSearchPlaceHolder: "ਤੁਸੀਂ ਅੱਜ ਕੀ ਦੇਖਣਾ ਚਾਹੋਗੇ?",
    gptSearch: "GPT ਖੋਜ",
    welcome: "ਸੁਆਗਤ ਹੈ",
    signout: "ਸਾਇਨ ਆਉਟ",
    signin: "ਸਾਈਨ ਇਨ ਕਰੋ",
    signup: "ਸਾਇਨ ਅਪ",
    name: "ਉਪਭੋਗਤਾ ਦਾ ਨਾਮ",
    email: "ਈ - ਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    signinMessage: "Netflix ਲਈ ਨਵੇਂ? ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ",
    signupMessage: "ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ? ਹੁਣੇ ਸਾਈਨ ਇਨ ਕਰੋ",
  },
  tamil: {
    search: "தேடு",
    gptSearchPlaceHolder: "இன்று நீங்கள் எதைப் பார்க்க விரும்புகிறீர்கள்?",
    gptSearch: "GPT தேடல்",
    welcome: "வரவேற்பு",
    signout: "வெளியேறு",
    signin: "உள்நுழையவும்",
    signup: "பதிவு செய்யவும்",
    name: "பயனரின் பெயர்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signinMessage: "Netflix க்கு புதியவரா? இப்பொது பதிவு செய்",
    signupMessage: "ஏற்கனவே பதிவு செய்யப்பட்டது? இப்போது உள்நுழையவும்",
  },
  kannada: {
    search: "ಹುಡುಕಿ",
    gptSearchPlaceHolder: "ನೀವು ಇಂದು ಏನನ್ನು ವೀಕ್ಷಿಸಲು ಬಯಸುತ್ತೀರಿ?",
    gptSearch: "GPT ಹುಡುಕಾಟ",
    welcome: "ಸ್ವಾಗತ",
    signout: "ಸೈನ್ ಔಟ್ ಮಾಡಿ",
    signin: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    signup: "ಸೈನ್ ಅಪ್",
    name: "ಬಳಕೆದಾರರ ಹೆಸರು",
    email: "ಇಮೇಲ್",
    password: "ಗುಪ್ತಪದ",
    signinMessage: "Netflix ಗೆ ಹೊಸಬರೇ? ಈಗ ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    signupMessage: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ? ಈಗ ಸೈನ್ ಇನ್ ಮಾಡಿ",
  },
  spanish: {
    search: "buscar",
    gptSearchPlaceHolder: "¿Qué te gustaría ver hoy?",
    gptSearch: "Búsqueda GPT",
    welcome: "Bienvenida",
    signout: "Desconectar",
    signin: "Iniciar sesión",
    signup: "Inscribirse",
    name: "Nombre de la usuaria",
    email: "Correo electrónico",
    password: "Contraseña",
    signinMessage: "¿Nuevo en Netflix? Regístrate ahora",
    signupMessage: "¿Ya registrado? Regístrate",
  },
};

export default lang;
